---
provisioner:
  name: chef_zero

platforms:
  - name: debian-8.3

suites:
  - name: base
    run_list:
      - recipe[dockerhp::base]
  - name: monitoring
    run_list:
      - recipe[dockerhp::monitoring]
  - name: jenkins
    run_list:
      - recipe[dockerhp::jenkins]
    verifier:
      name: shell
      command: open http://$KITCHEN_HOSTNAME:8080
